
    
    const MIKA_CONFIG = {
        whatsappNumber: "5491168280718",
        assetsPath: "./assets/" 
    };

function debounce(func,delay){let timeout;return function(...args){clearTimeout(timeout);timeout=setTimeout(()=>func.apply(this,args),delay)}}
function detectTouchDevice(){const isTouch=('ontouchstart' in window)||(navigator.maxTouchPoints>0)||(navigator.msMaxTouchPoints>0);if(isTouch){document.body.classList.add('has-touch')}}
function initializeLinks(){if(typeof MIKA_CONFIG==='undefined'||!MIKA_CONFIG.whatsappNumber){console.error("Error de Configuración: MIKA_CONFIG o whatsappNumber no están definidos.");return}
const whatsappLinks=document.querySelectorAll('.whatsapp-link');const waNumber=MIKA_CONFIG.whatsappNumber;whatsappLinks.forEach(link=>{const msg=link.getAttribute('data-msg')||"Hola, tengo una consulta sobre sus productos.";const encodedMsg=encodeURIComponent(msg);link.href=`https://wa.me/${waNumber}?text=${encodedMsg}`})}
const CLONES_COUNT=3;function setupIntersectionObserver(container,allItems){if(!container||allItems.length===0)return;const originalCount=allItems.length-(CLONES_COUNT*2);const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){const item=entry.target;const index=Array.from(allItems).indexOf(item);let instajumpPosition=null;if(index<CLONES_COUNT){instajumpPosition=allItems[originalCount+index].offsetLeft}else if(index>=allItems.length-CLONES_COUNT){let targetIndex=index-originalCount;instajumpPosition=allItems[targetIndex].offsetLeft}
if(instajumpPosition!==null){container.style.scrollBehavior='auto';container.scrollTo({left:instajumpPosition,behavior:'auto'});requestAnimationFrame(()=>{container.style.scrollBehavior='smooth'});return}
let normalizedIndex=index-CLONES_COUNT;const finalDisplayIndex=normalizedIndex+1;const originalItem=allItems[index];const currentTitle=originalItem.getAttribute('data-title')||'imagen';container.setAttribute('aria-label',`Carrusel, elemento visible: ${finalDisplayIndex} de ${originalCount}, ${currentTitle}`);allItems.forEach(i=>i.classList.remove('active'));item.classList.add('active')}})},{root:container,rootMargin:'0px -49% 0px -49%',threshold:0.01});allItems.forEach(item=>{observer.observe(item)})}
function cloneCarouselItems(container,originalItems){const originalArray=Array.from(originalItems);for(let i=0;i<CLONES_COUNT;i++){const clone=originalArray[originalArray.length-CLONES_COUNT+i].cloneNode(!0);clone.classList.add('is-clone-start');container.prepend(clone)}
for(let i=0;i<CLONES_COUNT;i++){const clone=originalArray[i].cloneNode(!0);clone.classList.add('is-clone-end');container.appendChild(clone)}}
function setupCarouselControls(){const carouselContainer=document.querySelector('.carousel-container');const prevButton=document.querySelector('.prev-arrow');const nextButton=document.querySelector('.next-arrow');const originalItems=document.querySelectorAll('.carousel-container > .carousel-item');if(!carouselContainer||originalItems.length===0||!prevButton||!nextButton)return;cloneCarouselItems(carouselContainer,originalItems);const allItems=document.querySelectorAll('.carousel-container > .carousel-item');function getScrollAmount(){const item=allItems[CLONES_COUNT];if(!item)return 0;const itemWidth=item.offsetWidth;const computedStyle=window.getComputedStyle(item);const marginRight=parseFloat(computedStyle.marginRight)||0;return itemWidth+marginRight}
function goToNext(){const scrollAmount=getScrollAmount();carouselContainer.scrollBy({left:scrollAmount,behavior:'smooth'});setTimeout(()=>{carouselContainer.focus()},500)}
function goToPrev(){const scrollAmount=getScrollAmount();carouselContainer.scrollBy({left:-scrollAmount,behavior:'smooth'});setTimeout(()=>{carouselContainer.focus()},500)}
function setInitialPosition(){const initialPosition=allItems[CLONES_COUNT].offsetLeft;carouselContainer.scrollTo({left:initialPosition,behavior:'auto'})}
setInitialPosition();prevButton.addEventListener('click',goToPrev);nextButton.addEventListener('click',goToNext);setupIntersectionObserver(carouselContainer,allItems);const debouncedSetInitialPosition=debounce(setInitialPosition,150);window.addEventListener('resize',debouncedSetInitialPosition)}
function setupMobileMenu(){const toggleButton=document.querySelector('.mobile-menu-toggle');const navMenu=document.querySelector('.main-nav');const navLinks=document.querySelectorAll('.main-nav a');if(!toggleButton||!navMenu)return;toggleButton.addEventListener('click',()=>{const isExpanded=toggleButton.getAttribute('aria-expanded')==='true';toggleButton.setAttribute('aria-expanded',!isExpanded);navMenu.classList.toggle('open');document.body.classList.toggle('no-scroll',!isExpanded)});navLinks.forEach(link=>{link.addEventListener('click',()=>{if(navMenu.classList.contains('open')){toggleButton.setAttribute('aria-expanded','false');navMenu.classList.remove('open');document.body.classList.remove('no-scroll')}})})}
function initApp(){detectTouchDevice();initializeLinks();setupMobileMenu();setupCarouselControls()}
document.addEventListener('DOMContentLoaded',initApp)